/*
  # Create Discovery Sessions Table

  ## Purpose
  Stores career discovery sessions generated by the AI for users.

  ## New Tables
  - `discovery_sessions`
    - `id` (uuid, PK) - Unique session identifier
    - `query` (text) - The user's original interest description
    - `result` (jsonb) - Full JSON result from Gemini AI (careers, roadmaps, skills)
    - `created_at` (timestamptz) - When the session was created

  ## Security
  - RLS enabled; public read/write allowed for anonymous usage (no auth required in MVP)
  - INSERT policy: anyone can create a session
  - SELECT policy: anyone can read sessions (used for sharing results via URL)
*/

CREATE TABLE IF NOT EXISTS discovery_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  query text NOT NULL,
  result jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE discovery_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can create a discovery session"
  ON discovery_sessions
  FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY "Anyone can read discovery sessions"
  ON discovery_sessions
  FOR SELECT
  TO anon
  USING (true);
